#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TicTacToe_Droid.Resource", IsApplication=true)]

namespace TicTacToe_Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040063
			public const int accent = 2130968675;
			
			// aapt resource value: 0x7f040064
			public const int accent_pressed = 2130968676;
			
			// aapt resource value: 0x7f040001
			public const int black = 2130968577;
			
			// aapt resource value: 0x7f04000f
			public const int button_danger = 2130968591;
			
			// aapt resource value: 0x7f040013
			public const int button_danger_disabled = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int button_danger_disabled_edge = 2130968596;
			
			// aapt resource value: 0x7f040010
			public const int button_danger_edge = 2130968592;
			
			// aapt resource value: 0x7f040018
			public const int button_danger_gradient_border = 2130968600;
			
			// aapt resource value: 0x7f040015
			public const int button_danger_gradient_dark = 2130968597;
			
			// aapt resource value: 0x7f040017
			public const int button_danger_gradient_light = 2130968599;
			
			// aapt resource value: 0x7f040016
			public const int button_danger_gradient_medium = 2130968598;
			
			// aapt resource value: 0x7f040019
			public const int button_danger_gradient_pressed_shadow = 2130968601;
			
			// aapt resource value: 0x7f040011
			public const int button_danger_pressed = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int button_danger_pressed_edge = 2130968594;
			
			// aapt resource value: 0x7f04003b
			public const int button_default = 2130968635;
			
			// aapt resource value: 0x7f04003f
			public const int button_default_disabled = 2130968639;
			
			// aapt resource value: 0x7f040040
			public const int button_default_disabled_edge = 2130968640;
			
			// aapt resource value: 0x7f04003c
			public const int button_default_edge = 2130968636;
			
			// aapt resource value: 0x7f040044
			public const int button_default_gradient_border = 2130968644;
			
			// aapt resource value: 0x7f040041
			public const int button_default_gradient_dark = 2130968641;
			
			// aapt resource value: 0x7f040043
			public const int button_default_gradient_light = 2130968643;
			
			// aapt resource value: 0x7f040042
			public const int button_default_gradient_medium = 2130968642;
			
			// aapt resource value: 0x7f040045
			public const int button_default_gradient_pressed_shadow = 2130968645;
			
			// aapt resource value: 0x7f04003d
			public const int button_default_pressed = 2130968637;
			
			// aapt resource value: 0x7f04003e
			public const int button_default_pressed_edge = 2130968638;
			
			// aapt resource value: 0x7f040002
			public const int button_edittext_border = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int button_edittext_disabled = 2130968579;
			
			// aapt resource value: 0x7f040030
			public const int button_info = 2130968624;
			
			// aapt resource value: 0x7f040034
			public const int button_info_disabled = 2130968628;
			
			// aapt resource value: 0x7f040035
			public const int button_info_disabled_edge = 2130968629;
			
			// aapt resource value: 0x7f040031
			public const int button_info_edge = 2130968625;
			
			// aapt resource value: 0x7f040039
			public const int button_info_gradient_border = 2130968633;
			
			// aapt resource value: 0x7f040036
			public const int button_info_gradient_dark = 2130968630;
			
			// aapt resource value: 0x7f040038
			public const int button_info_gradient_light = 2130968632;
			
			// aapt resource value: 0x7f040037
			public const int button_info_gradient_medium = 2130968631;
			
			// aapt resource value: 0x7f04003a
			public const int button_info_gradient_pressed_shadow = 2130968634;
			
			// aapt resource value: 0x7f040032
			public const int button_info_pressed = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int button_info_pressed_edge = 2130968627;
			
			// aapt resource value: 0x7f040046
			public const int button_inverse = 2130968646;
			
			// aapt resource value: 0x7f04004a
			public const int button_inverse_disabled = 2130968650;
			
			// aapt resource value: 0x7f04004b
			public const int button_inverse_disabled_edge = 2130968651;
			
			// aapt resource value: 0x7f040047
			public const int button_inverse_edge = 2130968647;
			
			// aapt resource value: 0x7f04004f
			public const int button_inverse_gradient_border = 2130968655;
			
			// aapt resource value: 0x7f04004c
			public const int button_inverse_gradient_dark = 2130968652;
			
			// aapt resource value: 0x7f04004e
			public const int button_inverse_gradient_light = 2130968654;
			
			// aapt resource value: 0x7f04004d
			public const int button_inverse_gradient_medium = 2130968653;
			
			// aapt resource value: 0x7f040050
			public const int button_inverse_gradient_pressed_shadow = 2130968656;
			
			// aapt resource value: 0x7f040048
			public const int button_inverse_pressed = 2130968648;
			
			// aapt resource value: 0x7f040049
			public const int button_inverse_pressed_edge = 2130968649;
			
			// aapt resource value: 0x7f040004
			public const int button_primary = 2130968580;
			
			// aapt resource value: 0x7f040008
			public const int button_primary_disabled = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int button_primary_disabled_edge = 2130968585;
			
			// aapt resource value: 0x7f040005
			public const int button_primary_edge = 2130968581;
			
			// aapt resource value: 0x7f04000d
			public const int button_primary_gradient_border = 2130968589;
			
			// aapt resource value: 0x7f04000a
			public const int button_primary_gradient_dark = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int button_primary_gradient_light = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int button_primary_gradient_medium = 2130968587;
			
			// aapt resource value: 0x7f04000e
			public const int button_primary_gradient_pressed_shadow = 2130968590;
			
			// aapt resource value: 0x7f040006
			public const int button_primary_pressed = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int button_primary_pressed_edge = 2130968583;
			
			// aapt resource value: 0x7f040051
			public const int button_purple = 2130968657;
			
			// aapt resource value: 0x7f040055
			public const int button_purple_disabled = 2130968661;
			
			// aapt resource value: 0x7f040056
			public const int button_purple_disabled_edge = 2130968662;
			
			// aapt resource value: 0x7f040052
			public const int button_purple_edge = 2130968658;
			
			// aapt resource value: 0x7f04005a
			public const int button_purple_gradient_border = 2130968666;
			
			// aapt resource value: 0x7f040057
			public const int button_purple_gradient_dark = 2130968663;
			
			// aapt resource value: 0x7f040059
			public const int button_purple_gradient_light = 2130968665;
			
			// aapt resource value: 0x7f040058
			public const int button_purple_gradient_medium = 2130968664;
			
			// aapt resource value: 0x7f04005b
			public const int button_purple_gradient_pressed_shadow = 2130968667;
			
			// aapt resource value: 0x7f040053
			public const int button_purple_pressed = 2130968659;
			
			// aapt resource value: 0x7f040054
			public const int button_purple_pressed_edge = 2130968660;
			
			// aapt resource value: 0x7f04001a
			public const int button_success = 2130968602;
			
			// aapt resource value: 0x7f04001e
			public const int button_success_disabled = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int button_success_disabled_edge = 2130968607;
			
			// aapt resource value: 0x7f04001b
			public const int button_success_edge = 2130968603;
			
			// aapt resource value: 0x7f040023
			public const int button_success_gradient_border = 2130968611;
			
			// aapt resource value: 0x7f040020
			public const int button_success_gradient_dark = 2130968608;
			
			// aapt resource value: 0x7f040022
			public const int button_success_gradient_light = 2130968610;
			
			// aapt resource value: 0x7f040021
			public const int button_success_gradient_medium = 2130968609;
			
			// aapt resource value: 0x7f040024
			public const int button_success_gradient_pressed_shadow = 2130968612;
			
			// aapt resource value: 0x7f04001c
			public const int button_success_pressed = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int button_success_pressed_edge = 2130968605;
			
			// aapt resource value: 0x7f040025
			public const int button_warning = 2130968613;
			
			// aapt resource value: 0x7f040029
			public const int button_warning_disabled = 2130968617;
			
			// aapt resource value: 0x7f04002a
			public const int button_warning_disabled_edge = 2130968618;
			
			// aapt resource value: 0x7f040026
			public const int button_warning_edge = 2130968614;
			
			// aapt resource value: 0x7f04002e
			public const int button_warning_gradient_border = 2130968622;
			
			// aapt resource value: 0x7f04002b
			public const int button_warning_gradient_dark = 2130968619;
			
			// aapt resource value: 0x7f04002d
			public const int button_warning_gradient_light = 2130968621;
			
			// aapt resource value: 0x7f04002c
			public const int button_warning_gradient_medium = 2130968620;
			
			// aapt resource value: 0x7f04002f
			public const int button_warning_gradient_pressed_shadow = 2130968623;
			
			// aapt resource value: 0x7f040027
			public const int button_warning_pressed = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int button_warning_pressed_edge = 2130968616;
			
			// aapt resource value: 0x7f040060
			public const int primary = 2130968672;
			
			// aapt resource value: 0x7f040061
			public const int primary_pressed = 2130968673;
			
			// aapt resource value: 0x7f040062
			public const int ripple = 2130968674;
			
			// aapt resource value: 0x7f04005c
			public const int thumbnail_background = 2130968668;
			
			// aapt resource value: 0x7f04005e
			public const int thumbnail_border = 2130968670;
			
			// aapt resource value: 0x7f04005f
			public const int thumbnail_font = 2130968671;
			
			// aapt resource value: 0x7f04005d
			public const int thumbnail_placeholder = 2130968669;
			
			// aapt resource value: 0x7f040000
			public const int white = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int activity_horizontal_margin = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int activity_vertical_margin = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int button_rounded_corner_radius = 2131034114;
			
			// aapt resource value: 0x7f05000e
			public const int font_large = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int font_medium = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int font_micro = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int font_small = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int margin_large = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int margin_medium = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int margin_small = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int padding_large = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int padding_medium = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int padding_micro = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int padding_small = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int thumbnail_rounded_corner_radius = 2131034115;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int BlackHole = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int button = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int button_danger = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int button_danger_gradient = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int button_danger_gradient_rounded = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int button_danger_rounded = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int button_default = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int button_default_gradient = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int button_default_gradient_rounded = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int button_default_rounded = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int button_info = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int button_info_gradient = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int button_info_gradient_rounded = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int button_info_rounded = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int button_inverse = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int button_inverse_gradient = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int button_inverse_gradient_rounded = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int button_inverse_rounded = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int button_primary = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int button_primary_gradient = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int button_primary_gradient_rounded = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int button_primary_rounded = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int button_purple = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int button_purple_gradient = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int button_purple_gradient_rounded = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int button_purple_rounded = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int button_success = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int button_success_gradient = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int button_success_gradient_rounded = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int button_success_rounded = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int button_warning = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int button_warning_gradient = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int button_warning_gradient_rounded = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int button_warning_rounded = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int Circle = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int Cross = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int Icon = 2130837540;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int box1 = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int box2 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int box3 = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int box4 = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int box5 = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int box6 = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int box7 = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int box8 = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int box9 = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int computerScore = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int myScore = 2131165195;
			
			// aapt resource value: 0x7f070004
			public const int textView1 = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int textView2 = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
